core: Implement new_pointer_event suggested_output
WayfireWM/wayfire pull request #1284
Opened 2021-09-13 01:31 UTC by kode54

This is a partial implementation, which is enough to get wayvnc
    cursor working on sessions with multiple outputs. It does not
    implement suggested_seat, but Wayfire does not appear to use
    that yet, anyway. Perhaps a simple check could be added to at
    least make sure that suggested_seat is either NULL or the one
    seat that Wayfire creates.

    Partial fix for #1283 , enough to get it basically working, but
    not exactly a full implementation of this functionality.

2021-09-14 00:35 UTC, any1 commented
Maybe it would be good to add a `// TODO` for the seat, so that it's less likely to be forgotten if/when wayfire gets multi-seat support.

2021-09-14 02:55 UTC, kode54 commented
Added the comment, it should hold over in case anyone else decides to try implementing it, in case it actually becomes relevant.

2021-09-19 06:12 UTC, ammen99 requested changes
Unfortunately, this wouldn't work. Device mappings are done here: https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/input-manager.cpp#L57

As soon as that code is run, any other mapping you create (like in this PR) will be overwritten.

How I think this problem can be fixed: You need to set the mapping option to the correct value. Then, you should `lock()` the option so that the config file doesn't overwrite it - there is a wf-config API for such scenarios.

2021-09-19 06:24 UTC, kode54 commented
Right, how do I do that? Why do I have to do that when you can just edit this PR?

2021-09-20 06:52 UTC, closed without merging