Port to wlroots 0.18.x
WayfireWM/wayfire pull request #2452
Opened 2024-08-26 12:17 UTC by soreau

Gotchas:

wl_drm was dropped, so clients must update. A notable one is libva, which stopped working with wlroots 0.18 until upgrading libva.

wlr_input_inhibit was dropped and as of now, there is no replacement.

2024-08-27 08:56 UTC, mark-herbert42 commented
Compiled 0.9 with this PR - works ok so far. Seems like the new wlroots is better in terms of battery life at least for firefox-youtube.

2024-08-27 09:03 UTC, soreau commented
> Compiled 0.9 with this PR - works ok so far. Seems like the new wlroots is better in terms of battery life at least for firefox-youtube.

Thanks for testing!

2024-09-03 17:43 UTC, killown commented
fuzz tests crash related to your branch
```
EE 03-09-24 14:41:52.567 - [src/api/wayfire/dassert.hpp:26] Adding a child node twice!
AddressSanitizer:DEADLYSIGNAL
=================================================================
==39316==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x58bbd4d01b7a bp 0x7ffde566ecd0 sp 0x7ffde566ddd0 T0)
==39316==The signal is caused by a WRITE memory access.
==39316==Hint: address points to the zero page.
    #0 0x58bbd4d01b7a in wf::print_trace(bool) ../src/debug.cpp:231
    #1 0x58bbd4da9c68 in wf::dassert(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../src/api/wayfire/dassert.hpp:27
    #2 0x58bbd4da9c68 in wf::scene::node_t::set_children_unchecked(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:136
    #3 0x58bbd4daa05e in wf::scene::floating_inner_node_t::set_children_list(std::vector<std::shared_ptr<wf::scene::node_t>, std::allocator<std::shared_ptr<wf::scene::node_t> > >) ../src/core/scene.cpp:120
    #4 0x58bbd4dc35dc in wf::scene::add_front(std::shared_ptr<wf::scene::floating_inner_node_t>, std::shared_ptr<wf::scene::node_t>) ../src/api/wayfire/scene-operations.hpp:38
    #5 0x58bbd4dc42b8 in wf::start_move_view_to_wset(nonstd::observer_ptr<wf::toplevel_view_interface_t>, std::shared_ptr<wf::workspace_set_t>) ../src/core/core.cpp:494
    #6 0x58bbd4dc4971 in wf::move_view_to_output(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool) ../src/core/core.cpp:532
    #7 0x58bbd4d0e8f0 in wf::window_manager_t::fullscreen_request(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::output_t*, bool, std::optional<wf::point_t>) ../src/core/window-manager.cpp:256
    #8 0x722e237436d1 in wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}::operator()(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool) const ../plugins/wm-actions/wm-actions.cpp:474
    #9 0x722e237436d1 in void std::__invoke_impl<void, wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}&, nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool>(std::__invoke_other, wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}&, nonstd::observer_ptr<wf::toplevel_view_interface_t>&&, bool&&) /usr/include/c++/14.2.1/bits/invoke.h:61
    #10 0x722e237436d1 in std::enable_if<is_invocable_r_v<void, wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}&, nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool>, void>::type std::__invoke_r<void, wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}&, nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool>(wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}&, nonstd::observer_ptr<wf::toplevel_view_interface_t>&&, bool&&) /usr/include/c++/14.2.1/bits/invoke.h:111
    #11 0x722e237436d1 in std::_Function_handler<void (nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool), wayfire_wm_actions_t::ipc_set_fullscreen::{lambda(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)#1}::operator()(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&) const::{lambda(nonstd::observer_ptr<wf::toplevel_view_interface_t>, bool)#1}>::_M_invoke(std::_Any_ [...]

2024-09-03 17:52 UTC, soreau commented
@killown How do you know this crash is related to this branch? It would also be helpful if you can explain how to reproduce the crash without the fuzz test.

2024-09-03 17:55 UTC, killown commented
> @killown How do you know this crash is related to this branch? It would also be helpful if you can explain how to reproduce the crash without the fuzz test.

because i am using your branch in the pkgbuild... not reproducible, this is how me and ammen99 did in the past, he just had the crash reports with no clue, it's up to you to fix it or not, but ammen99 could consider this a really issue before merging.

2024-09-27 11:25 UTC, ammen99 requested changes
Looking at https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4345, I believe we need to change all places which use xdg_surface.destroy events to xdg_popup/xdg_toplevel.destroy. 

Otherwise LGTM, thanks for the patience!

2024-09-27 11:31 UTC, soreau commented on src/core/output-layout.cpp
> +                // wlr_output_rollback(handle);
Yes, see this [later commit](https://github.com/WayfireWM/wayfire/pull/2452/commits/e4a450e3cb48b6c6a91eefb2885af932134b6592).

2024-09-27 11:35 UTC, soreau commented on src/view/xwayland.cpp
> +        if (!xwayland_surface->override_redirect)
If it is not done this way, wayfire will crash. I cannot find further reference at the moment.

2024-09-27 11:35 UTC, soreau commented on src/core/output-layout.cpp
> +                    wlr_output_commit_state(handle, &state);
Noted, will fix.

2024-09-27 11:36 UTC, soreau commented on plugins/ipc-rules/ipc-input-methods.hpp
> +            d["type"] = wlr_input_device_type_to_string(device->get_wlr_handle()->type);
From the 0.18 release notes:

"..drop wlr_input_device.{vendor,product}, these aren't super useful without the bus type. Compositors can still obtain this information from the libinput device if they want to."

2024-09-27 11:36 UTC, soreau commented on src/view/xdg-shell.cpp
> +    xdg_handle = wlr_xdg_shell_create(wf::get_core().display, 6);
Sounds good.

2024-09-28 12:31 UTC, soreau commented
> Looking at https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4345, I believe we need to change all places which use xdg_surface.destroy events to xdg_popup/xdg_toplevel.destroy.

I thought I caught them all but apparently xdg-toplevel is still using destroy events from the base xdg_surface (see last link). xdg_popups from [master](https://github.com/WayfireWM/wayfire/blob/master/src/view/xdg-shell.cpp#L411) vs. [track-wlroots](https://github.com/WayfireWM/wayfire/blob/track-wlroots/src/view/xdg-shell.cpp#L411) branch. Similarly for xdg_toplevel, [master](https://github.com/WayfireWM/wayfire/blob/master/src/view/xdg-shell/xdg-toplevel-view.cpp#L52) and [track-wlroots](https://github.com/WayfireWM/wayfire/blob/track-wlroots/src/view/xdg-shell/xdg-toplevel-view.cpp#L52)

2024-09-28 15:54 UTC, soreau commented on src/core/output-layout.cpp
> +                // wlr_output_rollback(handle);
I looked at this and what I think is best, is to call wlr_output_state_finish() and wlr_output_state_init() after each wlr_output_state_commit(), so I pushed a commit to do that. This way, we should never have to worry about rolling back states or potentially stale state data.

2024-09-28 15:55 UTC, soreau commented on plugins/ipc-rules/ipc-input-methods.hpp
> +            d["type"] = wlr_input_device_type_to_string(device->get_wlr_handle()->type);
I could use some help finding the call(s) to get the vendor/product id from libinput.

2024-09-28 16:51 UTC, soreau commented on plugins/ipc-rules/ipc-input-methods.hpp
> +            d["type"] = wlr_input_device_type_to_string(device->get_wlr_handle()->type);
I tried `libinput_device_get_id_{vendor|product}(wlr_libinput_get_device_handle(device->get_wlr_handle()));` but it always crashes.

2024-10-05 19:34 UTC, ammen99 commented on plugins/ipc-rules/ipc-input-methods.hpp
> +            d["type"] = wlr_input_device_type_to_string(device->get_wlr_handle()->type);
Devices are not necessarily libinput devices (especially in the wayland backend, you won't find a libinput device). So this needs to be in a check, and in the other cases we can set 'unknown' or -1 as a value.

2024-12-16 01:54 UTC, soreau commented
Since wlroots 0.18.2 has been released, I propose that we update to it before merging this.

2024-12-16 04:57 UTC, soreau commented on src/core/output-layout.cpp
> +                // wlr_output_rollback(handle);
Since you've pushed a commit to address this, resolving this conversation.

2024-12-18 13:26 UTC, ammen99 approved these changes
LGTM, also @soreau ran the tests and there are no regressions, so we can finally merge this :) Thanks for the patience and for your work @soreau :tada:

2024-12-18 14:09 UTC, soreau commented on plugins/ipc-rules/ipc-input-methods.hpp
> +            d["type"] = wlr_input_device_type_to_string(device->get_wlr_handle()->type);
Pushed a fix to get vendor/product ids for all devices when using libinput/drm backend.

2024-12-18 14:12 UTC, merged